version: '2'

services:
  r8000:
    image: 'carwestsam/redis-with-source'
    container_name: redis-cluster-entry
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8002:8002'
      - '8003:8003'
      - '8004:8004'
      - '8005:8005'
    volumes:
      - ./configure/8000/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  r8001:
    image: 'carwestsam/redis-with-source'
    volumes:
      - ./configure/8001/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "service:r8000"
  r8002:
    image: 'carwestsam/redis-with-source'
    volumes:
      - ./configure/8002/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "service:r8000"
  r8003:
    image: 'carwestsam/redis-with-source'
    volumes:
      - ./configure/8003/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "service:r8000"
  r8004:
    image: 'carwestsam/redis-with-source'
    volumes:
      - ./configure/8004/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "service:r8000"
  r8005:
    image: 'carwestsam/redis-with-source'
    volumes:
      - ./configure/8005/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "service:r8000"
